"""Minimal type stubs for oig_cloud_client.api.oig_cloud_api used by oig_cloud_mcp."""

from typing import Any, Dict, Optional, List

class OigCloudApi:
    _phpsessid: str
    _sample_path: Optional[str]
    box_id: Optional[str]

    def __init__(
        self, username: str, password: str, no_telemetry: bool = False
    ) -> None: ...
    async def authenticate(self) -> bool: ...
    async def get_stats(self) -> Dict[str, Any]: ...
    async def get_extended_stats(
        self, name: str, start_date: str, end_date: str
    ) -> Dict[str, Any]: ...
    async def get_notifications(self) -> List[Any]: ...
    async def set_box_mode(self, mode: Any) -> bool: ...
    async def set_grid_delivery(self, mode: Any) -> bool: ...
