# Minimal type stubs for the `mcp` package used by oig_cloud_mcp
from typing import Any, Dict, Tuple, Optional

class ClientSession:
    def __init__(self, read_stream: Any, write_stream: Any) -> None: ...
    async def __aenter__(self) -> "ClientSession": ...
    async def __aexit__(
        self, exc_type: Optional[type], exc: Optional[BaseException], tb: Optional[Any]
    ) -> Optional[bool]: ...
    async def initialize(self) -> None: ...
    async def list_tools(self) -> Any: ...
    async def call_tool(self, tool_name: str, arguments: Dict[str, Any]) -> Any: ...
